apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-mysql-pvc
  namespace: wordpress-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-wordpress-pvc
  namespace: wordpress-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
